//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linapot
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_grid
    {
        public string c_name { get; set; }
        public int client_id { get; set; }
        public System.DateTime date { get; set; }
        public int reason { get; set; }
        public int type { get; set; }
        public int id { get; set; }
        public string reasonexp { get; set; }
        public string typeexp { get; set; }
        public string l_name { get; set; }
        public int location_id { get; set; }
        public int personel_id { get; set; }
        public string username { get; set; }
    }
}
