//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace linapot
{
    using System;
    using System.Collections.Generic;
    
    public partial class interaction
    {
        public int client_id { get; set; }
        public int pesonel_id { get; set; }
        public System.DateTime date { get; set; }
        public int reason { get; set; }
        public string details { get; set; }
        public int type { get; set; }
        public int id { get; set; }
        public string reasonexp { get; set; }
        public string typeexp { get; set; }
    
        public virtual client client { get; set; }
        public virtual personel personel { get; set; }
    }
}
